name: WDIO Test
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: Install dependencies
      run: npm ci
    - name: Install all dependencies
      run: npm install --with-deps
    - name: Run wdio tests
      run: npx wdio
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: wdio-report
        path: allure-reults/
        retention-days: 30
